### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lishine** [leerob/leerob.io#125]
Hi,
About your post going-serverless-next-firebase-now.
Isn't the cold start at Now is a problem for SEO and user experience?

**Comment by leerob** [comment]
Hey @lishine 👋 

By utilizing proper caching, having a cold start isn't a problem. For example, on my site, I cache all the static assets (including JS and CSS) [here](https://github.com/leerob/leerob.io/blob/master/now.json#L13) and the cache will be invalidated when they change. 

If you'd like to see an example of a Next.js + Now monorepo site, check out [BeyondHQ](https://beyondhq.co/). You'll see there's no issues with SEO or UX.

**Comment by lishine** [comment]
Glad to read your reply!
So Now has cache config for routes, great to know!
My site is on GitHub pages lishine.github.io, github cache-control fixed at 10minutes.
But thinking about it. You mean actually that the cold start is solved by CDN caching. Which is revelation for me.
It is great, so for static site cold start not an issue.
While cold start is an issue for dynamic sites - the ones with server because you cannot cache the html. And for api that is serverless on lambdas.

**Comment by leerob** [comment]
Yep, absolutely! I hope that answers your question. Let me know if you have any others and I'll try my best to help 🎉
