### ISSUE TITLE
Next.js Sentry source maps

### ISSUE THREAD

**Issue by Vadorequest** [leerob/leerob.io#163]
Hello @leerob, I've read your tutorial at https://leerob.io/blog/configuring-sentry-for-nextjs-apps (through https://forum.sentry.io/t/sentry-webpack-plugin-and-next-js-sourcemaps/4153/5)

I would love your help on https://github.com/UnlyEd/next-right-now/issues/28

NRN is an OSS boilerplate, which features Sentry. But source maps don't work perfectly yet, I believe you could be quite helpful on this matter! 😉 (let me know if you have time and are willing to help!)

Thank you.

**Comment by leerob** [comment]
Hey!

At first glance, nothing sticks out to me as wrong without diving in. If I have some time, I'll see if I can look at it. 

Still waiting for this to abstract all these problems away -> https://github.com/zeit/next.js/tree/canary/packages/next-plugin-sentry

**Comment by Vadorequest** [comment]
Thanks for taking a look! 

I took a quick look at next-plugin-sentry and don't really see how it's gonna help with source maps, seems like some basic helper for logging errors.

**Comment by leerob** [comment]
Gonna close this cause I doubt I'll be able to figure it out. Sentry setup is way too confusing with Next. Getting away from `getInitialProps` should help the Sentry setup _a lot_. Then there's a more clear separation of what's on the client and the server.

Ideally, this is all baked into the Sentry plugin, even source maps 👍

**Comment by Vadorequest** [comment]
Yeah, I agree with you... It's non-trivial. But it should be.

>Getting away from getInitialProps should help the Sentry setup a lot.

Do you mean there is something going on that'll make it happen? Or is it just a thought of you?

**Comment by leerob** [comment]
I'm just saying it reduces a lot of complexities that come from `getInitialProps` running on both client _and_ server. This introduces a lot of edge cases into the Sentry set up.
