### ISSUE TITLE
Add RSS/Atom feeds

### ISSUE THREAD

**Issue by franky47** [leerob/leerob.io#178]
It would be nice to have syndication feeds to subscribe to new articles (even though you have a newsletter, some people might prefer RSS/Atom).

I have added RSS & Atom syndication in my [own blog](https://github.com/franky47/francoisbest.com/blob/7996fb6b1b9a79a2bbb88ba8f9ec4eab822ae6c5/src/utility/blog.ts#L59-L113), and I can help integrate it here.

It boils down to generating the XML/JSON files from the list of published posts, so it needs a list of posts with the following metadata:
  - Is it published or a draft
  - Publication date
  - The URL
  - An optional preview text that is shown in feed readers

It looks like we can infer all this metadata from the frontmatter, so the idea would be, at build time:
- Glob the files under `/pages/blog`
- Parse their metadata (using [`frontmatter`](https://www.npmjs.com/package/frontmatter))
- Filter only on the posts with a `publishedAt` value
- Build the URL from the file path (as done in `generate-sitemap`)
- Feed that to [`feed`](https://www.npmjs.com/package/feed)
- Generate the syndication feeds

There are two ways we can do the generation:
1. using [Next.js 9.3 `getStaticPaths`](https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation) in a separate route (eg: `/pages/[feeds].js`)
or
2. Use the same technique as for the sitemap, and have an external script generate the pages and store the feed files into `/public` before build time.

**Comment by leerob** [comment]
Thanks for all the info! ❤️

**Comment by jatin2003** [comment]
That'll be Awesome! Btw Thanks @leerob for Awesome Site!

**Comment by franky47** [comment]
After refactoring my blog with lots of ~stolen code~ inspiration from this repository, it would be easier than previously stated to generate the feeds, thanks to `next-mdx-enhanced`.

We can:
1. Inject whatever [extra data](https://github.com/franky47/francoisbest.com/blob/360c16cff4cf4c18988a0e6ec624c18c9f0e6f3c/next.config.js#L45-L61) we may need in the frontMatter for feed generation
2. Retrieve all the frontMatters using `babel-plugin-import-glob-array`
3. Pass that to the [feed generation script](https://github.com/franky47/francoisbest.com/blob/next/src/scripts/generateFeeds.ts)

The question is: where to call this?

On my blog, I use the `getStaticProps` call on the post index page to generate both the sitemap and the feeds, but its a bit hacky.

I like your approach of running it in `next.config.js`, I did not go for that option as I use TypeScript and it's a bit of a pain to use in the Next.js config file, but for your blog this could work well.

For the frontMatter extension, things that would differ would be:
- OG image URL (I use a predefined path, but yours can be inferred from the frontMatter itself, just extended to an absolute URL)
- Absolute URLs: we can use `https://leerob.io` as a base for all absolute URLs (as done in the sitemap), however Vercel previews may have resources pointing to production.

**Comment by vvo** [comment]
@franky47 I tried to follow your path, but trying to fs.write from getStaticProps on vercel fails with

`Unhandled error during request: Error: ENOENT: no such file or directory, open '/vercel/workpath0/public/feed/articles.json'`

any idea why/how to solve that? It seems we can only use fs.write in build step

**Comment by franky47** [comment]
@vvo maybe you need to [`mkdir -p`](https://www.npmjs.com/package/make-dir) your path's `dirname` first ?

Also there are weird tricks using paths where `__filename` does not work, and you have to use `process.cwd()` to resolve to the correct repo root.

**Comment by vvo** [comment]
Thanks, are you, yourself, hosted on Vercel and generating the feeds from a Vercel build?

**Comment by franky47** [comment]
No, mine is statically exported (using `next export`) and hosted on Surge.sh. Here's a link to the feed generation: https://github.com/franky47/francoisbest.com/blob/next/src/scripts/generateFeeds.ts

**Comment by vvo** [comment]
@franky47 I directly used your script and you were right, I had to push public/feed/CORS to Vercel so the directory exists. Thanks a lot :)
