### ISSUE TITLE
Google analytics tracking needs consent

### ISSUE THREAD

**Issue by injms** [leerob/leerob.io#180]
👋 Hi! You've got a great website, full of super-great articles. 

The one thing that should be changed is that the website tracks people without asking - which is against the GDPR "cookie law". This states that all websites that collect data from EU citizens, regardless of where the website is based, require a person's informed consent before storing cookies on a user’s device and / or tracking them. 

One solution is to track page views without setting a cookie - this tracks views rather than people so there wouldn't be a need to ask permission. This is what Netlify Analytics and Fathom do. The analytics would still get page views (not that any analytics software is needed for your increment views counter) and insights into technology use, but the analytics wouldn't be able to track an individual person's journey through the site.

Another is to implement a method that asks people to actively opt in and allow tracking. I've seen this get less points of data - anything from 10% to 40% of the pre-ask numbers - but it's easier to see how people move through the site.

Another is to block EU users... please don't do this!

Privacy is something that should be available to everyone - and I hope you help make it available for people who visit your site and want to learn from your articles.

**Comment by leerob** [comment]
Hey! 👋 Thanks for the note. 

I've been working on moving over to Fathom, but haven't had time to finish it yet. It's on my todo list!

**Comment by injms** [comment]
That's super news! Fantastic 😃
