### ISSUE TITLE
Switch to WWW Subdomain?

### ISSUE THREAD

**Issue by lukefernandez** [leerob/leerob.io#192]
Hey Lee! Thanks for all of the great content! Your blog has inspired me to set up one of my own. I just wanted to reach out with a couple of recommendations that might make your site even better.

Going through your blog, I noticed that you host on your apex domain, `leerob.io`. I came across [this post](https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/) from Netlify a while back, and I found it convincing enough to move my site to the `www` subdomain. Check it out. I think they make some good points. I looked into this when I noticed a lot of the top companies use the `www` subdomain. You can find additional information [here](https://www.yes-www.org/why-use-www/) and [here](https://www.bjornjohansen.com/www-or-not).

I also recommend adding a wildcard redirect to your project settings. Right now, if you go to something like `awesome.leerob.io`, you'll get a Vercel error page, which isn't the best user experience. If you want an example of how to do this, this is how I have mine set up right now:

<img width="759" alt="Screen Shot 2020-06-15 at 11 07 48 AM" src="https://user-images.githubusercontent.com/8265202/84674240-b7620c00-aef8-11ea-8e58-1f643a48e059.png">

I think it provides a rather seamless user experience.

Anyway, that's all I had. Keep up the great work!

**Comment by leerob** [comment]
Hey Luke! Thanks for the detailed message.

I gave all three articles a read. While there were some interesting points made, I didn't feel strongly enough about any to justify switching things over. Some of the specific benefits like sharing cookies across subdomains just don't apply to me.
As for the wildcard, I do utilize some subdomains for completely separate applications (e.g. [photos.leerob.io](photos.leerob.io)) so for now, I'll probably keep this as is. 

I appreciate all of the information!
