### ISSUE TITLE
Moving constants to a config file to make the template easy to use

### ISSUE THREAD

**Issue by Sletheren** [leerob/leerob.io#193]
Hello lee,
Firstly, thank you very much for the effort you put into making this and the fact that you made it public so others can have a boost if they wanna set up their own portfolio/blog.

I was intending to rewrite my VueJS portfolio to something different following the JAM stack, so decided to with NextJS instead of Nuxt, and I stumbled upon this project of yours and I immediately liked the way you made (exactly what I was thinking for my own blog) so i cloned your repo and tweaked it a bit, 

I have a added quite a lot of refactoring/improvements, and I was thinking that I could make a PR to move some static values to a config file, so it becomes easy for others to reuse this.

I can as well add a little script to generate `robots.txt` and a `CV.pdf` in case someone wants that to be generated from a page.

Just let me know if it's okay and I will submit a PR,
Thank you for your efforts :+1:

**Comment by leerob** [comment]
Hey @Sletheren 👋 

I'm glad you've found my site helpful. While I appreciate the thought, I'm happy with the way it's currently set up. 

Thanks again for the note!
