### ISSUE TITLE
Store Dark Mode preferences in Local Storage

### ISSUE THREAD

**Issue by deadcoder0904** [leerob/leerob.io#194]
Otherwise I have to constantly switch dark mode on every article I click :)

**Comment by franky47** [comment]
This would cause a FOUC (flash of unthemed content) when loading the website, which may not be desirable. Dark mode should stick around for local navigation between articles however, and only reset to light mode when reloading the page.

FYI, the [upcoming TypeScript release](https://github.com/chakra-ui/chakra-ui/issues/696) of ChakraUI is supposed to solve those [FOUC colorMode issues](https://github.com/chakra-ui/chakra-ui/issues/349).

**Comment by deadcoder0904** [comment]
It wasn't working because I started binge-reading his articles bcz there were so good. And I have a habit of opening in `New Tab` so it didn't work.

It works while navigating as it should :)

**Comment by leerob** [comment]
It turns out that dark mode is pretty tricky when using CSS-in-JS. To properly implement in, you likely need to use CSS variables as well.

https://joshwcomeau.com/gatsby/dark-mode/
https://github.com/chakra-ui/chakra-ui/issues/349#issuecomment-631465423

**Comment by deadcoder0904** [comment]
Yep already read Josh’s blog post & opened up an issue on Chakra UI a few days ago too. Not sure it’s solvable with Chakra https://github.com/chakra-ui/chakra-ui/pull/908#issuecomment-648881758

**Comment by sarthaktexas** [comment]
can we make it so it gets system setting for dark/light mode? i'm having to set it to dark mode every time i open it up.

**Comment by deadcoder0904** [comment]
@sarthaktexas ohh yeah i think that might work as chakra provides an option now with `preferred-color-scheme`

**Comment by sarthaktexas** [comment]
yup! should I make a pull request?

**Comment by leerob** [comment]
@sarthaktexas I believe that will require updating Chakra to v1 – if you're open to that, I'd love assistance!

**Comment by Rodman-Sw** [comment]
@leerob Actually I don't think you need to do that, let me see what can I do

**Comment by leerob** [comment]
@Rodman-Sw My point is that you shouldn't need to do anything custom once you upgrade to Chakra v1. Since I will be doing that eventually, I'd prefer to stick with that rather than something custom. Does that make sense? 

https://next.chakra-ui.com

**Comment by AkashRajpurohit** [comment]
Hey @leerob I recently build a project with Next and Chakra UI with v1.0, today I just pushed the persisting of color mode on my project [Github Emojis](https://github-emojis.vercel.app/). If you are planning to upgrade Chakra-UI to 1.0, Do you mind I if try to implement the similar on [leerob.io](https://leerob.io) as well?

**Comment by leerob** [comment]
Yeah, I'd love help migrating to v1! @AkashRajpurohit

**Comment by leerob** [comment]
Fixed here -> https://github.com/leerob/leerob.io/pull/239
