### ISSUE TITLE
Comment section is incompatible with dark mode

### ISSUE THREAD

**Issue by sibasishm** [leerob/leerob.io#216]
Hey, I have noticed that you added the comment section recently. However the text color is not getting transformed upon theme change. Please look into it.

![image](https://user-images.githubusercontent.com/16509307/89707711-5b62b380-d98e-11ea-8bd2-03933ed97323.png)

**Comment by leerob** [comment]
Good catch! Totally forgot about dark mode 😢 

I'll need to update my new product [Fast Feedback](https://fastfeedback.io) to support it. Thanks for reporting this.
