### ISSUE TITLE
Is the blogs are being published automaticly?

### ISSUE THREAD

**Issue by higgleio** [leerob/leerob.io#220]
So I am super happy looking at the amount of open source projects people are contributing to. I got to this project trying to auto mate my blogs which at the moment statically hosted on s3.
So for blog posts, I am creating a md file on lambda and pushing the md files to s3.

I wonder if you have a automate system for this already? If not any idea how we can achieve it with Vercel?

Thanks again for making this open source.

**Comment by leerob** [comment]
Hey! You won't need to manually push any files. It's all based around GitHub. 

1. Add some new Markdown content locally
2. Push to GitHub
3. The [Vercel GitHub Integration](https://vercel.com/github) builds the Next.js application
4. Deploys to prod!

**Comment by higgleio** [comment]
Ahh, I meant, that's what I wanted to avoid. I was asking more of a CMS system. :)
You publish from a different system and it shows up in your blog without any code change or manual work. I am sorry if I dont make sense.

**Comment by leerob** [comment]
Gotcha. Nope, this blog does not use a CMS. I would recommend checking out the Next.js example blog with whichever CMS you want to use!

https://github.com/vercel/next.js/tree/canary/examples/cms-sanity
