### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by davidbarratt** [leerob/leerob.io#228]
Would you mind adding a license to this project? May I recommend the [AGPL-3](https://www.gnu.org/licenses/agpl-3.0.md)?

**Comment by leerob** [comment]
I'm gonna be honest, I hate the legalize of licenses like this when dealing with personal projects. I understand there's a need to cover your ass (as with all legalize) but when it's a personal site, most of it feels pointless. 

Maybe I'll just add a license saying:

- You are free to use this code as inspiration
- Please do not copy it directly
- Crediting the author (me) is apprecited

**Comment by davidbarratt** [comment]
That seems fine. The problem is is that without a license at all, it's illegal to copy it or make derivatives from it at all.

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/blob/master/LICENSE.txt
