### ISSUE TITLE
Firebase error in api/page-views.js

### ISSUE THREAD

**Issue by larbisahli** [leerob/leerob.io#231]
Hello, i was reading your awesome blogs about next.js and i found bug in your **page-views.js** api route in blog _Create a Dashboard with Next.js API Routes - Google Analytics API_
 
![Screenshot 2020-09-24 162643](https://user-images.githubusercontent.com/52937392/94167686-b2f8a800-fe84-11ea-9b2a-09f3ecca645a.png)

Visiting the **api/page-views.js** route.

![Screenshot 2020-09-24 163012](https://user-images.githubusercontent.com/52937392/94167798-d58ac100-fe84-11ea-968b-c0678bdf6339.png)

That route is not protected and i would love to learn from you how you can protect next.js api routes.

Cheers

**Comment by leerob** [comment]
Whoops 😓  That was from here. https://github.com/leerob/leerob.io/pull/229

You can disregard it! You can protect your route by checking a secret environment variable and returning an error if they don't match.
