### ISSUE TITLE
Sticky nav covering headings

### ISSUE THREAD

**Issue by rhnmht30** [leerob/leerob.io#242]
The image below shows a slight issue when clicking on an internal link on a blog page.
It hides under the sticky navbar.
 
![sticky-nav-issue](https://user-images.githubusercontent.com/40598945/101597753-268a6a00-3a1d-11eb-8ec0-72c5d6696dab.gif)

I'll be happy to fix this if come across a solution. Just wanted to let you know. 
Thanks

**Comment by leerob** [comment]
Ahhh yes. I had this in the old version and accidentally removed it. Will look at the PR now.
