### ISSUE TITLE
Set theme based on user's OS setting

### ISSUE THREAD

**Issue by tilda** [leerob/leerob.io#244]
Default should be set using a media query (e.g. `prefers-color-scheme: dark`). IMO it would be a much better experience to have it set like that (while still having the option to switch themes if wanted).

**Comment by leerob** [comment]
It already does this via https://github.com/pacocoursey/next-themes 👍

**Comment by tilda** [comment]
Hm, it doesn't seem to work for me, at least on Windows with Edge. Tried clearing local storage and it seems to believe my system theme is set to light. (Of course, it isn't.)

**Comment by leerob** [comment]
If you can repro and find out some more info, might be worth opening an issue on next-themes 🙏 I'm guessing it's related to Edge.

**Comment by tilda** [comment]
Not sure if it's `next-themes`, as the live example site on "System" setting does detect my theme correctly... ah well, this might be interesting to look into. Thank you for responding!

**Comment by leerob** [comment]
Oh, very interesting! Maybe it is me then... strange. Will look more, thank you!
