### ISSUE TITLE
React hook form for form state

### ISSUE THREAD

**Issue by apoorvmote** [leerob/leerob.io#279]
I have been using react-hook-form for managing form state. I was previously using Formik. And I am able to do pretty much everything I wanted with react-hook-form that I was doing with formik at better performance with less complexity of code. 

https://leerob.io/blog/react-state-management

I don't have strong opinion on where you would place them in your table. But I do have strong opinion that it should be mentioned somewhere because its really that good. I am not affiliated with react hook form in any way. Just a big fan.

**Comment by leerob** [comment]
I do enjoy using React Hook Form, _but_ I don't think it's radically different from Formik. Especially with Formik v3 coming soon. Is there something I'm missing?

**Comment by apoorvmote** [comment]
I wasn't aware about Formik v3. I am original fan of Formik. I just hated the complex higher order component for setting up simple form. That experience was made much easier with react hook form while increasing performance and writing less code. But just as react developers expressed publically that they are scared of other frameworks like Vue and Swelte that they had to do something groundbreaking to stay competetive. I am exited to see what will Formik V3 bring.
