### ISSUE TITLE
Add a bookmarks page

### ISSUE THREAD

**Issue by leerob** [leerob/leerob.io#285]
I already use Raindrop to manage my bookmarks, so maybe I'll make them public? They have an API

**Comment by heyfirst** [comment]
Hey @leerob, you might know they have an API (https://developer.raindrop.io/)

- We can get all raindrops from collection id here (https://developer.raindrop.io/v1/raindrops/multiple#get-raindrops)
- We need to make a call for OAuth2 then attach that token into request, This one I think we can make it simply via serverless functions. 🙂

By the way, I am finding the good bookmark to replace [Pocket](https://getpocket.com/). Thanks for sharing you use Raindrop!

Cheers.

**Comment by leerob** [comment]
For now, I'm going to close as not planning to do this. Maybe in the future 😄
