### ISSUE TITLE
Add Unixify caveat for Windows on sitemap build

### ISSUE THREAD

**Issue by austinhale** [leerob/leerob.io#293]
Just an FYI -- if you're following the sitemap build process on your [nextjs-sitemap-robots](https://leerob.io/blog/nextjs-sitemap-robots) blog post, it may be worth mentioning that if you're on a Windows machine, `globby` is [not going to work](https://github.com/sindresorhus/globby/issues/155) for the `path.join('')` step, unless you either do a regex replace or use something like [unixify](https://www.npmjs.com/package/unixify). 

```
// generate-sitemap.js

const unixify = require('unixify');

... 

// Unixify is needed for when you're on a Windows machine
const route = path === '/index' ? '' : unixify(path);
```

**Comment by leerob** [comment]
Thank you, I will update and link back here!

**Comment by aaron-soto** [comment]
> 
> 
> Thank you, I will update and link back here!

Coming from your Blog Post, is this the case if developing on Windows machine but hosting on Vercel?

**Comment by quick007** [comment]
Not sure you need a sitemap on your local machine- you can probably disable it locally
