### ISSUE TITLE
Is it necessary to use MDXProvider from @mdx-js/react 

### ISSUE THREAD

**Issue by payapula** [leerob/leerob.io#297]
Hi Leerob!

First of all thanks 🎉  for creating and providing such awesome content on Nextjs. Surely it helps many people like me in getting started with Next. 

I see your blog is using `next-mdx-remote` which uses [MDXProvider](https://mdxjs.com/getting-started#mdxprovider) from `@mdx-js/react` [under the hood](https://github.com/hashicorp/next-mdx-remote#replacing-default-components). I also notice you surrounded all the components in the same provider on **_app.js**. 

```js
export default function App({ Component, pageProps }) {
  useAnalytics();

  return (
    <ThemeProvider attribute="class">
      <MDXProvider components={MDXComponents}>
        <Component {...pageProps} />
      </MDXProvider>
    </ThemeProvider>
  );
}
```

I did remove this `MDXProvider` and restarted the application, the MDX content are getting rendered as expected. So is it necessary to use this explicitly? If we can remove this then we don't need to include `@mdx-js/react` package.

**Comment by leerob** [comment]
Good catch! `@mdx-js` is a peer dep, so still needed though 👍
