### ISSUE TITLE
Use analytics API to avoid firestore for posts view count

### ISSUE THREAD

**Issue by angelhodar** [leerob/leerob.io#313]
Hey! Today I have started to use umami analytics which is an open source project. I have commented an idea in [this](https://github.com/mikecao/umami/issues/638) issue about exposing an API to get data programatically which can be extremely helpful to use in blog post view count! Plausible already has this feature that you can see [here](https://plausible.io/docs/stats-api#:~:text=The%20Plausible%20Stats%20API%20offers,your%20sites%20through%20the%20API), and fathom seems they are going to include it in version 3. I suppose you have already thought about this but just to let you know!

**Comment by leerob** [comment]
Hey! Yeah I could definitely move everything to one service, but they're all been added as I learned and taught new things. I probably won't change it for now, but maybe in the future :)
