### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by omaralsoudanii** [leerob/leerob.io#321]
Hey @leerob 

I am using your method of aliasing react as preact, working great so far. However with the latest nextjs updates the bundle size doubled and it seems to me the aliasing stopped working.

I checked your site as well, same thing. The first JS load files got doubled in size and the browser now actually detect the site as react ( before it didn't) 

Do you have some input about this? reverting to next v10.2.0 seems to work though

**Comment by leerob** [comment]
Which release?

**Comment by leerob** [comment]
Was not able to confirm this, bundle size remains the same for what's on `main` currently and when I updated to `next@latest` 👍

**Comment by omaralsoudanii** [comment]
Hi @leerob 

I'm probably mistaken. Looking at previous deployments next was generating more chunks on page load, e.g: common.js 

Now I think it just put everything in a file called main.js which is the largest (85kb without cache) 

since it seems it has nextjs core and other deps you have.

The weird thing is I've been using your trick to alias react to preact on the client side and the site was detected as preact instead of react .

( I use a browser extension called wappalyzer, not accurate 100% but it gives you some info)


Now it's actually being detected as React.

To be honest with caching it doesn't matter in terms of load, I was just curious about the alias behaviour and if it might have changed in the new webpack.
