### ISSUE TITLE
Preact conflict with next/image

### ISSUE THREAD

**Issue by valse** [leerob/leerob.io#322]
Hi Lee... how are you? Just to let you know that I saw some loading issues using preact with next/image component: if you check a blog post for example you could see that all the images are loaded on page load and then by the intersection observer too!
Removing preact it works like expected ;)

**Comment by leerob** [comment]
Hmm, I am seeing the images loaded immediately but not loaded twice by the intersection observer. Could you share?

**Comment by valse** [comment]
You're right; I had the "disable cache" option enabled and subsequent image requests were not being taken from the cache

**Comment by omaralsoudanii** [comment]
@leerob Guess this also solved related to this #339

**Comment by leerob** [comment]
Correct, solved!
