### ISSUE TITLE
copy to clipboard in code 

### ISSUE THREAD

**Issue by Deep-Codes** [leerob/leerob.io#330]
Would be great to have to have Copy to Clipboard in `Code` 

I have implemented this in my project , I can work on this if needed!

![copy](https://user-images.githubusercontent.com/61158210/120932061-e711b180-c711-11eb-8c75-5dfbbd8099ec.gif)

**Comment by leerob** [comment]
Hey! Yeah would love to have this 🙏

**Comment by Deep-Codes** [comment]
> Hey! Yeah would love to have this 🙏

You would need to wrap your code in the <Code> component in Mdx btw.

If that's ok for you.

**Comment by leerob** [comment]
Addressed with https://github.com/leerob/leerob.io/pull/382
