### ISSUE TITLE
`Toggle Light Mode` aria label missing on Sun icon

### ISSUE THREAD

**Issue by deadcoder0904** [leerob/leerob.io#338]
https://github.com/leerob/leerob.io/blob/3c66f3bb5b09f95fd972586e76613613781d49e9/components/Container.js#L53

You can also add `title="Activate light mode"` to show a little pop-up when hovered over the icons.

Thank you for Dark Mode. I was facing a weird issue `Warning: Expected server HTML to contain a matching <button> in <div>` which I think looking at your code might solve.

**Comment by leerob** [comment]
I kept "toggle" as it implies both light and dark 😄
