### ISSUE TITLE
RemarkGFM esm Error

### ISSUE THREAD

**Issue by souravrs999** [leerob/leerob.io#357]
Hi lee how did you successfully import remarkGfm ?
I'm trying to do the same but i'm having this error.

`Error: Must use import to load ES Module: /home/sourav/Desktop/Blog/learn-nextjs/node_modules/remark-gfm/index.js`

Did i miss a step or something i'm not able to figure it out. Tnx

**Comment by leerob** [comment]
Hey! I'm using the ESM support built into Next.js to allow using the latest version of `remark-gfm`, which is ESM only.

https://github.com/leerob/leerob.io/blob/main/next.config.js#L2
