### ISSUE TITLE
View Counter with planetscale

### ISSUE THREAD

**Issue by vahidtakro** [leerob/leerob.io#366]
I get this error while opening my url:
https://www.myurl.com/api/views:

```
{"message":"target: newdatabase.-.primary: vttablet: rpc error: code = NotFound desc = Table 'newdatabase.views' doesn't exist (errno 1146) (sqlstate 42S02) (CallerID: unsecure_grpc_client): Sql: \"select SUM(count) as total from views\", BindVars: {}"}
```

![Calkpture](https://user-images.githubusercontent.com/40500566/132542224-ef988090-beb0-4f33-a607-2d11c1b154b3.JPG)

**Comment by vahidtakro** [comment]
I just figured out I didn't add tables and columns, I found out how to create tables through [this youtube video](https://www.youtube.com/watch?v=YqBG5rFP4Ic) (thanks for that), but still I don't know what tables and rows should I create.
something like this:
```
CREATE TABLE `views` (
  `count` varchar(255) NOT NULL
);
```
but what values?

**Comment by leerob** [comment]
```sql
CREATE TABLE `views` (
`slug` varchar(128) NOT NULL,
`count` bigint NOT NULL DEFAULT '1',
PRIMARY KEY (`slug`)
)

CREATE TABLE `guestbook` (
`id` bigint NOT NULL AUTO_INCREMENT,
`email` varchar(256) NOT NULL,
`body` varchar(500) NOT NULL,
`created_by` varchar(256) NOT NULL,
`created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
`updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
PRIMARY KEY (`id`)
)
```

I'll add this to the post!

**Comment by vahidtakro** [comment]
Thanks! but unfortunately this didn't fix the issue :(
I can at least get 200 on checkly, but null.
and my posts are still showing --- instead of view numbers.

![kjCalkpture](https://user-images.githubusercontent.com/40500566/132704051-be5855d4-5565-4128-b954-48b2ffb8c288.JPG)

![Capkkture](https://user-images.githubusercontent.com/40500566/132704079-ec1a840e-29c1-4325-9924-6c2799c985ad.JPG)

**Comment by leerob** [comment]
It doesn't seem like you have the same setup as me, so I'm not sure what is going on there.
