### ISSUE TITLE
Font inconsistent behavior 

### ISSUE THREAD

**Issue by omaralsoudanii** [leerob/leerob.io#383]
@leerob 

Take a look at the screenshot below, some quotes differs from the others, not sure where else this is happening. 

This is on chrome using Android mobile,  screenshot taken from this page https://leerob.io/snippets/youtube

Probably a search and replace in all folders would find more. 

![Screenshot_20211005-170159.jpg](https://user-images.githubusercontent.com/7079173/136039520-c3645b36-8baa-4918-9bce-2449b213df10.jpg)

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/commit/cf3869f69006b02239fed4d3122874a752bbb602
