### ISSUE TITLE
Command failed with exit code 1.

### ISSUE THREAD

**Issue by rodrigoricky** [leerob/leerob.io#398]
Website automatically crashes when opening localhost

![image](https://user-images.githubusercontent.com/89636767/139011838-68a23cb3-c5a3-4450-a1a3-a2f0243f45a3.png)

**Comment by leerob** [comment]
Closing since it's a known ContentLayer issue 👍

**Comment by leerob** [comment]
Wait, this is already fixed in ContentLayer! Nice.
