### ISSUE TITLE
(request) Document your mdx syntax highlighting setup

### ISSUE THREAD

**Issue by NateRadebaugh** [leerob/leerob.io#399]
# (request) Document your mdx syntax highlighting setup

I'm wondering how/if you've got a SSR syntax highlighting solution without a front-end bundled `prism.js` and `prism-react-renderer`.

https://leerob.io/blog/mdx no longer seems to be up to date.

**Comment by leerob** [comment]
I'm now using `contentlayer`, which is like Prisma, but for your content.

https://github.com/leerob/leerob.io/blob/main/contentlayer.config.ts#L84-L103

**Comment by leerob** [comment]
Planning to do a live stream soon walking through various updates to this repo!
