### ISSUE TITLE
Potential improvement for guestbook

### ISSUE THREAD

**Issue by dextermb** [leerob/leerob.io#410]
Hey,

I recently watched your YouTube video on prisma/planetscale.
It's great to see technologies that make it easier to integrate into any codebase.

https://github.com/leerob/leerob.io/blob/039b46e023a1a18c7fe99abee2fc5314e3d53b37/pages/api/guestbook/index.ts#L9-L15

I noticed that you're always loading all guestbook entries even if someone is attempting to create one.
Surely loading all entries should only be done within the GET method?

Cheers!

**Comment by leerob** [comment]
Great catch!

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/commit/6ec707315e75797a6aa4915751bd9b42d97457c1
