### ISSUE TITLE
Question: blog writing process

### ISSUE THREAD

**Issue by jahirfiquitiva** [leerob/leerob.io#412]
Hey Lee

I wanted to ask, when creating a new blog post, do you use any software to write your markdown before putting it into the project files? If so, which app do you use?

Or is it all done there directly?

Thanks in advance!

**Comment by leerob** [comment]
Hey! I usually write in Notion, since I have everything else in there, and then move to Markdown to post 👍

**Comment by jahirfiquitiva** [comment]
Thanks! 😀
