### ISSUE TITLE
I could delete all the guestbook entries!

### ISSUE THREAD

**Issue by collegewap** [leerob/leerob.io#417]
https://github.com/leerob/leerob.io/blob/0de2e793c0107b6fc3fb19a1329a9f69d3e521dd/pages/api/guestbook/%5Bid%5D.ts#L29-L41

Here you are checking for name instead of email in the unauthorized check. If I just change my name to anyone's from the existing comments, I could delete them!

**Comment by leerob** [comment]
Thanks! https://github.com/leerob/leerob.io/commit/e83f455e5802fa07c3f7f35aa948dce86950d657
