### ISSUE TITLE
完善时间线

### ISSUE THREAD

**Issue by plxdhong** [leerob/leerob.io#419]
https://github.com/leerob/leerob.io/blob/f23948b4fd4d9ee9aa435d24effd5f7a377c3947/components/Timeline.tsx#L42

**Comment by leerob** [comment]
I believe that translates to "perfect timeline" - so thank you! Although I'm unsure what the issue is, feel free to elaborate.

**Comment by plxdhong** [comment]
> I believe that translates to "perfect timeline" - so thank you! Although I'm unsure what the issue is, feel free to elaborate.

This is a comment I made while reading the source code of your blog, which was incorrectly published by the VS Code plug-in. Your timeline is well designed, and I admire the experience.
