### ISSUE TITLE
Queries related to using GA and Input focus.

### ISSUE THREAD

**Issue by cupboard319** [leerob/leerob.io#422]
Hi @leerob , I've few queries related to this project:
1. How are you managing/writing blog, I mean are you using any CMS or writing directly .md file?
2. Could you plz. guide me how to connect Google Analytics instead of Fathom (avoiding due to only paid version availability).
3. Where should I change to update the focus color of Input https://prnt.sc/21cvxy2 Tried to looking into many files but didn't find a way.

Sorry, for asking noob questions, I am in beginner stage of learning.

**Comment by leerob** [comment]
1. Writing directly in Markdown.
2. https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics
3. `focus:ring-blue-500 focus:border-blue-500 `

**Comment by cupboard319** [comment]
> 1. Writing directly in Markdown.
> 2. https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics
> 3. `focus:ring-blue-500 focus:border-blue-500 `

@leerob Thanks a lot for your response and suggestions! For the (3.) I already updated `focus:ring-green-500 focus:border-green-500` but it doesn't changes anything. Apart from this everything is updated. I've also updated all the theming from blue to green.

Is there anything I am missing? https://prnt.sc/23a5y1n
