### ISSUE TITLE
@nickluger feedback on Next.js

### ISSUE THREAD

**Issue by leerob** [leerob/leerob.io#428]
@nickluger couldn't find a good way to reach out to you, but saw you had some feedback on Next.js - mind connecting with me here or on Twitter? 🙏

**Comment by nickluger** [comment]
Hey @leerob, nice to meet you! I really enjoyed your talks at Next 12 conf!

Yes, I recently had some feedback for Brandon Bayer on his Blitz.js pivot, that involved Next.js. For context: We use Next.js (pure) and Blitz.js in production and are evaluating Remix currently for a relaunch of our web application in Q1 2022.

**Comment by leerob** [comment]
Would you mind emailing me `lee@vercel.com` with that feedback on Next/Vercel? Thank you so much 🙏 ❤️
