### ISSUE TITLE
Revue Api Error

### ISSUE THREAD

**Issue by cupboard319** [leerob/leerob.io#434]
![image](https://user-images.githubusercontent.com/94604790/147811782-6ed68434-c02f-4025-9614-a182ebc607dd.png)

Hi @leerob 
Prisma schema is generated
`REVUE_API_KEY` is added in `.env` file still getting this error.
Could you plz. guide, if I am missing something? Previously, it was working fine.

**Comment by leerob** [comment]
Hey! Are you sure you have the correct API key? Have you added any logging on the response from Revue?

**Comment by cupboard319** [comment]
> Hey! Are you sure you have the correct API key? Have you added any logging on the response from Revue?

@leerob Yes, API Key is correct. I am not aware of any logging response from Revue?

**Comment by cupboard319** [comment]
@leerob I did tried with fresh clone and just adding the `REVUE_API_KEY` in `.env` and updated https://www.getrevue.co/profile/user in `Newletter.tsx` still got the same error but I checked your live website subscribe is working fine. It's weird because I haven't changed anything in the fresh cloned repo. Could you plz. help me in solving this issue.

```js
event - compiled client and server successfully in 240 ms (373 modules)
wait  - compiling /api/auth/[...nextauth]...
event - compiled client and server successfully in 195 ms (376 modules)
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
error - FetchError: invalid json response body at https://www.getrevue.co/api/v2/subscribers reason: Unexpected end of JSON input
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 64 ms (377 modules)
error - FetchError: invalid json response body at https://www.getrevue.co/api/v2/subscribers reason: Unexpected end of JSON input
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
error - FetchError: invalid json response body at https://www.getrevue.co/api/v2/subscribers reason: Unexpected end of JSON input
wait  - compiling /api/subscribe...
event - compiled client and server successfully in 191 ms (378 modules)
error - FetchError: invalid json response body at https://www.getrevue.co/api/v2/subscribers reason: Unexpected end of JSON input
error - FetchError: invalid json response body at https://www.getrevue.co/api/v2/subscribers reason: Unexpected end of JSON input
```

**Comment by leerob** [comment]
It might be your Revue account? I'm not sure 😞

**Comment by aeelbeyoglu** [comment]
I have also the same issue, could you please look at the API again?

**Comment by a35026** [comment]
Have used Postman for cross-checking, same Revue API auth error
Apparently they have issues with authenticating **newly added users**
Also found [tens of people](https://community.zapier.com/general-questions-3/401-authentication-failed-error-when-connecting-to-revue-13160) experiencing auth issues with Revue during last weeks

Are there any alternatives to Revue?

**Comment by erwinowak** [comment]
I have exactly the same problem.
I tried to make a test application that will handle getrevue and it's the same problem

**Comment by leerob** [comment]
I'm going to close this issue - I am unsure the issue with Revue, but I have other code snippets on my side if you would prefer to use a different provide. I don't believe it's my code, as it's working okay here. Sorry about that!
