### ISSUE TITLE
Table heading are not styled correctly in dark mode

### ISSUE THREAD

**Issue by vimtor** [leerob/leerob.io#435]
[Past, Present, and Future of React State Management](https://leerob.io/blog/react-state-management#form-state)

https://user-images.githubusercontent.com/36263538/148391923-54decc30-0672-4504-b945-a1c2abd64829.mp4

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/commit/4facc656eebfa76c7f3a5b5848206e5a61465667

**Comment by leerob** [comment]
Thank you!
