### ISSUE TITLE
Explore using GitHub as a CMS

### ISSUE THREAD

**Issue by leerob** [leerob/leerob.io#436]
https://github.com/sw-yx/swyxkit/issues/10

**Comment by shreshthmohan** [comment]
djyde created a blog engine that uses GitHub issues as CMS. Relevant code here: https://github.com/djyde/sairin/blob/master/packages/core/src/index.tsx

**Comment by leerob** [comment]
Picked Sanity instead: https://github.com/leerob/leerob.io/pull/496
