### ISSUE TITLE
Building failed 

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#439]
I've tried several times and filled to build. Please help

**Comment by XahidEx** [comment]
Error occurred prerendering page "/tweets". Read more: https://nextjs.org/docs/messages/prerender-error
--
19:52:38.860 | TypeError: Cannot read property 'reduce' of undefined
19:52:38.860 | at getTweets (/vercel/path0/.next/server/chunks/401.js:257:24)
19:52:38.861 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
19:52:38.861 | at async getStaticProps (/vercel/path0/.next/server/pages/tweets.js:49:20)
19:52:38.861 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:438:20)
19:52:38.862 | at async /vercel/path0/node_modules/next/dist/export/worker.js:275:36
19:52:38.862 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
19:52:39.027 | info  - Generating static pages (34/137)

**Comment by XahidEx** [comment]
It worked fine 2-3 months ago. But you've updated so many things and I wanted to redeploy. And now It's failed to deploy.

**Comment by XahidEx** [comment]
![Screenshot_20220120-204653_Brave](https://user-images.githubusercontent.com/88249321/150361583-5e46fbae-12d7-4cd3-843c-2a422d580c95.jpg)
![Screenshot_20220120-204656_Brave](https://user-images.githubusercontent.com/88249321/150361596-89a63989-cd06-4b8d-88da-a220e11d6baa.jpg)
& more

**Comment by leerob** [comment]
If you're not using Tweets, maybe just delete that route?

**Comment by XahidEx** [comment]
I've tried with the standard installation from your repo. It gave me an error. Then I've made a custom installation. Same errors. And then I've added recommended Environments and still the same issue.

**Comment by XahidEx** [comment]
Would you please check If It's an issue with package updates. I'm a newbie. So I can't really deal with things. 😪
Or suggest to me what to do. It's not even deploying when I'm trying to deploy from your repo just like you've shown in your video. It worked fine before.
