### ISSUE TITLE
Mailchimp API: Missing the required parameter 'listId' when calling

### ISSUE THREAD

**Issue by jordanlambrecht** [leerob/leerob.io#445]
hey, thanks for the great tutorial ([https://leerob.io/blog/mailchimp-next-js](https://leerob.io/blog/mailchimp-next-js))

I triple checked my .env to make sure the audience ID was correct, but I still receive the following return error when hitting the submit button:

`Missing the required parameter 'listId' when calling`

Any ideas?

**Comment by leerob** [comment]
Does it work if you hard code the ID there instead of an env var? That would make it clear the env var is the issue 👍

**Comment by jordanlambrecht** [comment]
@leerob haha I'm an idiot. I added the .env variable but never restarted the server. That's on me. I'll close it out shortly, but while I have you, I'm now getting: `getaddrinfo ENOTFOUND server.api.mailchimp.com` any ideas?
