### ISSUE TITLE
Multiple Users for Spotify?

### ISSUE THREAD

**Issue by jordanlambrecht** [leerob/leerob.io#447]
Hey!

Quick question. I'm building out a 'team' page where everyone has a profile. I think it would be dope to display their top tracks or currently listening to status. I have everything setup to show my stuff, but is there an easy way to authorize additional users?

**Comment by leerob** [comment]
Hey! That sounds neat. Unfortunately I am not sure. You might need to switch to a different auth strategy like allowing the user to OAuth.
