### ISSUE TITLE
Guestbook form accepts a string of spaces

### ISSUE THREAD

**Issue by kevinzunigacuellar** [leerob/leerob.io#452]
Hello Lee 👋

First of all, awesome website and blog.
Personally, I have used your Spotify blog post to set up authentication and authorization using the Spotify API. I find it easier to understand than the actual docs. Thank you for that. Having said that here's the issue:

### Problem
The guestbook form can accept a string of empty spaces.

<img width="740" alt="Screen Shot 2022-02-13 at 11 38 21 PM" src="https://user-images.githubusercontent.com/46791833/153801087-910a7a90-03d5-4c47-8c96-369b7a1328b1.png">

**Comment by leerob** [comment]
Good feedback! Maybe someone would be interested in making a PR for this 😄

**Comment by kevinzunigacuellar** [comment]
I would like to take this small project if it's available as a way to say thanks.
