### ISSUE TITLE
Recommendation required

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#462]
The easiest way to use Google Analytics or plausible.io?
Because I've tried several times adding the Javascript snippet. But never worked. Please help. I've even followed the method provided by NextJs docs. Now I have a question, Is there anything that is preventing snippet to get the traffic?

**Comment by leerob** [comment]
This repo uses Fathom - it's worked pretty well! Tbh I don't check it anymore though haha, probably should remove it.
