### ISSUE TITLE
small bug I think

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#481]
Maybe you can see and notice there are some differences between colors in white. I've noticed that on Remote Desktop. And maybe I've noticed that before on my Phone once. Don't know what's the issue at all. But I think you'd understand when you look closely. Yellow shades
![Screenshot_20220522-141727_Microsoft Remote Desktop](https://user-images.githubusercontent.com/88249321/169685560-1b561561-93e0-4daa-9b67-2dfec3c24828.png)
![Screenshot_20220522-141740_Microsoft Remote Desktop](https://user-images.githubusercontent.com/88249321/169685564-18b193ff-7d1d-43af-a94c-2d66d3ee1828.png)
![Screenshot_20220522-140710_Microsoft Remote Desktop](https://user-images.githubusercontent.com/88249321/169685570-b0c2c474-71cf-4812-a464-b28b1d1394c7.png)

**Comment by leerob** [comment]
Closing as this seems expected 👍
