### ISSUE TITLE
Vercel Deploy Issue

### ISSUE THREAD

**Issue by dsvesair** [leerob/leerob.io#487]
I want to build and live using Vercel, but I'm getting an error. I tried yan I tried npm. I tried clone the repo but it didn't work. 

<img width="809" alt="image" src="https://user-images.githubusercontent.com/17431092/172024913-f97f35b4-33e6-4a2f-8603-a4408a05e5db.png">

or 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/17431092/172027561-e29dce33-676a-4d34-8b5f-a0076715d240.png">

"Error: Command "yarn run build" exited with 1"

I haven't made any changes to your repo. When I say deploy in the template part of Vercel, I get the same error, so it doesn't work without any modifications. Or can you help?

**Comment by leerob** [comment]
Ah yes, I think the issue here is that it's failing because of the twitter API key needed. I can make this optional.

**Comment by dsvesair** [comment]
I think the blog and twitter section should be optional. Or it would be great if you offer that as an option.

**Comment by leerob** [comment]
Fixed!

**Comment by dsvesair** [comment]
The problem still continues. Not deployed on Vercel&Netlify
