### ISSUE TITLE
RSS isn't deployed

### ISSUE THREAD

**Issue by BasixKOR** [leerob/leerob.io#491]
Hi! Thank you for the excellent content you've written; I enjoy reading your articles, and I've subscribed to your blog via RSS.

However, I've noticed the `/feed.xml` doesn't work like it used to. Instead, it gives me... _451 – Unavailable For Legal Reasons_ (lol). Could you check the RSS configuration for fellow RSS subscribers?

**Comment by alany411** [comment]
This issue is most likely due to pnpm not running postbuild scripts. There's an open issue here. [pnpm/pnpm#2891](https://github.com/pnpm/pnpm/issues/2891)

**Comment by leerob** [comment]
I removed the postbuild script here -> https://github.com/leerob/leerob.io/pull/496
