### ISSUE TITLE
500 on not existing blog path

### ISSUE THREAD

**Issue by Alex289** [leerob/leerob.io#499]
I saw you switched to Sanity and was really impressed by it. I tried it myself and found out if u go to a non existing blog post like blog/cool you get a 500. 

To fix this you need to add this to the getStaticProps on the [slug].tsx:
`if (!post) {
    return {
      notFound: true,
    }
  }` 

I hope I could help you 😄

**Comment by leerob** [comment]
Thank you! 🙏
