### ISSUE TITLE
Not deployed on Vercel 

### ISSUE THREAD

**Issue by dsvesair** [leerob/leerob.io#507]
Hello,

I have been trying to deploy this project in vercel and netlify for a long time, but I have not been successful. I suggested it to some of my friends, but they couldn't either. It's really hard to deploy. 

<img width="826" alt="image" src="https://user-images.githubusercontent.com/17431092/176559664-de4b632d-5fb7-4e03-9f3d-876cf78ce851.png">

It's trying to deploy forever this way or it throws an error. 

Can you make a video on how to deploy to Vercel? Because it is not deployed with one click. + When we add your repo to vercel, it does not deploy.

**Comment by KasperAndersson** [comment]
@dsvesair Looks like you're missing the env variables, as @XahidEx points out. Have a look at this https://github.com/leerob/leerob.io/blob/main/.env.example#L28, and [this article](https://nextjs.org/docs/basic-features/environment-variables) might come in handy.

**Comment by leerob** [comment]
Thanks folks, going to mark this as resolved.
