### ISSUE TITLE
page url will be shown when it expects to be title

### ISSUE THREAD

**Issue by arviinmo** [leerob/leerob.io#518]
lately i clone this repo (the older version without SANITY) and customize it for myself.
every things works fine in localhost but when I deploy it on Vercel, I get a weird bug. When I go to the Vercel links, I see the URL link will be shown in the title section on the top where it is supposed to be title.

[the version i cloned](https://github.com/leerob/leerob.io/tree/5a823c563e495d58f168a872647fb370c46a22c6)
[Vercel demo link](https://arvin.vercel.app/)

**Comment by arviinmo** [comment]
@XahidEx @KasperAndersson @leerob

**Comment by leerob** [comment]
Hey! I'm not sure. Feel free to post back here if you figure it out 🙏

**Comment by arviinmo** [comment]
Hi @leerob,
just change next.config and vercel.json and deploy it again.
it works fine now
