### ISSUE TITLE
Guestbook entry delete button bug

### ISSUE THREAD

**Issue by heykapil** [leerob/leerob.io#519]
https://github.com/leerob/leerob.io/blob/f7060f463001bc527e2e104d8bac6ace16a106e2/components/Guestbook.tsx#L33

Anyone with same name and different email has option to delete entries of other person. For example: if i do change my display name to leerob then i can delete the first entry of the guestbook by @leerob like this.

![Screenshot (112)](https://user-images.githubusercontent.com/101615305/181232774-2e3a0048-28a0-424e-b301-8084a20f7786.png)

**Possible Fix:**
- Use `email` instead of `name` of user.

**Comment by alex289** [comment]
Nice catch, but for this the guestbook api has to return the email for the entry.

I moved the getSession to the top and added this to the mapping here: https://github.com/leerob/leerob.io/blob/f7060f463001bc527e2e104d8bac6ace16a106e2/pages/api/guestbook/index.ts#L17

`email: session?.user?.email === entry.email ? entry.email : null,`

So there will be no security issue with exposing user emails
