### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#520]
Hey Lee,
I've got an idea. Hope you'd also like it.
If you make a custom signin page with more providers. Including Twitter, Google, and Facebook. (Guestbook) At least Twitter. It would be awesome. Because I see how much you like Twitter. And another reason why I'm talking about making a custom sign-in page is so that it would also help improve SEO score.
![20220727_212526](https://user-images.githubusercontent.com/88249321/181296082-28a9ec75-7395-4841-9a98-84ae3cb8badb.png)

(I've tired some providers showed in nextauth documentation. Twitter provider didn't work for me.)

**Comment by leerob** [comment]
Hey! I'd recommend building off a next-auth example. I don't plan to add any other providers here currently.
