### ISSUE TITLE
Is there any reasons why use tailwindcss in dependencies instead of devdependencies?

### ISSUE THREAD

**Issue by tatoMa** [leerob/leerob.io#522]
I have checked package.json and found that tailwindcss and its plugin are in dependencies but not in devdependencies. Are these lib normally in devdependencies or there is a reason you do this way?

**Comment by artcabrera** [comment]
Because tailwindcss works only in development. It literally creates a css file at build time and that file is the one used in production.

**Comment by leerob** [comment]
This is the recommendation from Tailwind 👍
