### ISSUE TITLE
NextAuth version 4.10.3 not compatible with NodeJs version 18

### ISSUE THREAD

**Issue by nikhilPatilGit** [leerob/leerob.io#523]
To get around this issue, i'm using NVM (https://github.com/nvm-sh/nvm) to switch from version 18 to version 16 for this specific project.

Note:- Installing nvm on mac m1 is bit different, to get help follow this blog :- 
https://dev.to/httpjunkie/setup-node-version-manager-nvm-on-mac-m1-7kl

**Comment by leerob** [comment]
This should be fixed now in latest versions 👍
