### ISSUE TITLE
Unable to read properties of undefined (reading 'slice') in top-tracks api

### ISSUE THREAD

**Issue by thecoderebel** [leerob/leerob.io#524]
I cloned the original repo and I have customized the secrets and client-id. But when I am trying to run the dev in local, it throwing an error that doesn't contain the `items` in the JSON response. I tried to log it as well. 

@leerob can you help me resolve this issue?

<img width="580" alt="image" src="https://user-images.githubusercontent.com/91749535/183303714-a1a3661f-ea6f-49ba-97be-87faf675d9bc.png">

**Comment by orensrauch** [comment]
Same here
@leerob your help is needed

**Comment by leerob** [comment]
Hey! I'm not sure – this is likely an issue with your local Spotify setup. I would recommend following the tutorial again.

https://leerob.io/blog/spotify-api-nextjs
