### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Somanyu** [leerob/leerob.io#544]
### Google Analytics API not able to fetch data
When I try to fetch the data from Google Analytics API it shows this 
``{"error":"User does not have sufficient permissions for this profile."}``
I have given proper .env variables wherever required. After searching in the net, I have found out that to use Google Cloud products I need to be under an "Organization". Without this I will be not able to enable G-Suite Domain-Wide Delegation. Is there any other option to use use the API.

**Comment by leerob** [comment]
Hey, I'm not sure what's happening here - sorry about that.
