### ISSUE TITLE
Trouble Finding Sanity Environment Variables

### ISSUE THREAD

**Issue by 1RB** [leerob/leerob.io#552]
![image](https://user-images.githubusercontent.com/86501179/204096276-f499e935-1714-41bd-9821-99021f07ae28.png)

Is `NEXT_PUBLIC_SANITY_DATASET` in the form of: `https://<projectId>.api.sanity.io/v2021-06-07/data/query/<dataset>` or just `<dataset>`?

And where do I find `SANITY_PREVIEW_SECRET` and `SANITY_STUDIO_REVALIDATE_SECRET`

Thanks in advance

**Comment by alex289** [comment]
The dataset variable is containing the name of the dataset you configured and the two secrets are one made up by you. (The revalidate secret must be set in the sanity dashboard if you are using it)

**Comment by 1RB** [comment]
so the dataset variable should be `production` for example and where in the dashboard do i set the revalidate secret

**Comment by alex289** [comment]
Exactly. The secret can be set under the api settings in Sanity. You need to create a new webhook and set the secret to the one in the environment variable.

**Comment by 1RB** [comment]
sorry last question, what do i set the URL to? 
![image](https://user-images.githubusercontent.com/86501179/204100984-2876c2ff-6738-4582-8a00-c74eb3fd7d56.png)

**Comment by alex289** [comment]
`https://your-host.vercel.app/api/revalidate`

**Comment by 1RB** [comment]
thank you so much
