### ISSUE TITLE
Need Some Answers ?

### ISSUE THREAD

**Issue by innovatorved** [leerob/leerob.io#553]
1. Could you please tell me how to add code highlighting from Sanity markdown ?
like this -
![image](https://user-images.githubusercontent.com/65329423/206002028-ab471b95-5ef9-448c-8d7c-3f4b21cf3ccf.png)

2. how to add file name in top of code ?
like this - 
![image](https://user-images.githubusercontent.com/65329423/206002174-b81fb5fd-4906-46fe-98d4-15a06a67c50c.png)

3. how to write Pros and Cons - (Red and Green)

**Comment by shivamjjha** [comment]
1. for highlighting package `rehype-prism-plus` is used. See https://github.com/timlrx/rehype-prism-plus
2. for adding code titles, `rehype-code-titles` is used. See https://github.com/rockchalkwushock/rehype-code-titles
3. for pros and cons simply different components are used

For usage on `1` and `2` see https://github.com/leerob/leerob.io/blob/675ba074e873a85f1ee6a0d195f7d20312e62b4e/lib/mdx.ts#L11-L25

For `3` simple tailwind classes are used. See https://github.com/leerob/leerob.io/blob/675ba074e873a85f1ee6a0d195f7d20312e62b4e/components/ProsCard.tsx#L1

**Comment by innovatorved** [comment]
Thankyou @shivamjjha
