### ISSUE TITLE
Revue is getting shut down. 

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#557]
I just got the mail. Revue is getting shut down. 🙂

**Comment by plxdhong** [comment]
yeah, it's time to use alternatives.
Buttondown?
Mailchimp?
Here are some alternatives:
[Code Snippets](https://leerob.io/snippets)

**Comment by leerob** [comment]
It has been removed!

I'm on Substack -> https://leerob.substack.com/
