### ISSUE TITLE
Sanity Schema

### ISSUE THREAD

**Issue by aiden-z-source** [leerob/leerob.io#561]
Where do I find the guide for setting up Sanity with this? What is the Sanity Schema etc?

**Comment by leerob** [comment]
I'm planning to move back to local MDX very soon, so I likely won't be adding this.

**Comment by aiden-z-source** [comment]
Out of curiosity, how come?

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/issues/497#issuecomment-1382882968
