### ISSUE TITLE
broken heading anchor links

### ISSUE THREAD

**Issue by yasinmiran** [leerob/leerob.io#565]
https://user-images.githubusercontent.com/25561152/215358142-c2c669d1-ea64-4f4a-9e77-55d5e2cc7e60.mov

`rehype-slug` is working as expected. I suspect this is something to do with `rehype-autolink-headings` or the following 🤔: - 

https://github.com/leerob/leerob.io/blob/63b6aae31800a2e79f4181b894bcbd5b87970337/components/mdx.tsx#L9-L17

**Comment by leerob** [comment]
Good catch - thank you!

https://github.com/leerob/leerob.io/commit/3b75c463aa183a2a4d468c3bf8ec245a11261091
