### ISSUE TITLE
[optional] sitemap + robots.txt

### ISSUE THREAD

**Issue by JesseKoldewijn** [leerob/leerob.io#567]
The dev-side lib I use on my own and projects at my job should do just fine, not sure how it handles the new appDir stuff but might be handy anyway.

npmPackage: https://www.npmjs.com/package/next-sitemap

**Comment by JesseKoldewijn** [comment]
I mainly added this issue because I noticed this topic being mentioned in the readme todos. 👌

**Comment by leerob** [comment]
We're working on better sitemap support - for now, I pushed up a static sitemap 👍

**Comment by JesseKoldewijn** [comment]
Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?

**Comment by ruchernchong** [comment]
> Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?

Seems to suggest so here:   NProgress.configure({ showSpinner: false });

**Comment by ruchernchong** [comment]
> Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?

Seemed to suggest so here: https://github.com/leerob/leerob.io#todo

**Comment by JesseKoldewijn** [comment]
> > Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?
> 
> Seemed to suggest so here: https://github.com/leerob/leerob.io#todo

Yeah as mentioned before, I've read that but it seemed to me more like it was rather more directed towards his website itself imo.

**Comment by ruchernchong** [comment]
> > > Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?
> > 
> > 
> > Seemed to suggest so here: https://github.com/leerob/leerob.io#todo
> 
> Yeah as mentioned before, I've read that but it seemed to me more like it was rather more directed towards his website itself imo.

Oh, you mentioned before. Anyway, no point speculating now. Just want and see what he does.

**Comment by JesseKoldewijn** [comment]
> > > > Do you mean there will be sitemap and robots.txt gen in Next.js in the near future?
> > > 
> > > 
> > > Seemed to suggest so here: https://github.com/leerob/leerob.io#todo
> > 
> > Yeah as mentioned before, I've read that but it seemed to me more like it was rather more directed towards his website itself imo.
> 
> Oh, you mentioned before. Anyway, no point speculating now. Just want and see what he does.

Same! 😁👍
