### ISSUE TITLE
[Improvement]: Implement accessible link to go back to `/blog` route when user access specific article

### ISSUE THREAD

**Issue by esau-morais** [leerob/leerob.io#569]
### Description
I don't know if it was just me, but I felt stuck for a ms with the new UI, once I finished reading your latest article (btw I love it) and wanted to go back to the `blog` route. It would be great to add a link at the `/blog/:slug` route to go back imo. I don't know if this is actually an acceptable issue, but I'll let here my suggestion.

### Possible solution
Add close to the date (might be at the top or to the left) a `Link` from `next/link`.

![https://leerob.io/blog/funding-open-source](https://user-images.githubusercontent.com/55207584/215632269-315f5332-a52c-4a1c-9207-ba7e8470e22f.png)

**Comment by giuseppe-g-gelardi** [comment]
> You could just click on Blog [sidebar].

You could. But there is also no scroll restoration so you’re back at the top. 

I agree with @esau-morais , It would be nice if there was a floating “back” button to bring you back (with scroll restoration) where you left off. 

Another suggestion for @leerob would be to have the header fixed at the top of the page so you don’t have to scroll back to the top to go back.
