### ISSUE TITLE
Errors when going to the applications blog link 

### ISSUE THREAD

**Issue by mdixon47** [leerob/leerob.io#573]
Hello, I am running the application, and I am getting this error when I click on the blog link:
 errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'undefined

**Comment by leerob** [comment]
Can you provide more information? Does it work in CodeSandbox for you?

**Comment by mdixon47** [comment]
Unfortunately no. Error with exit code 127

**Comment by mdixon47** [comment]
I am also having this issue here. ![Screenshot 2023-02-07 at 5 13 37 PM](https://user-images.githubusercontent.com/995331/217378899-47de67cd-e008-4376-80eb-705f2d71e221.png)

**Comment by SDBurt** [comment]
So it wasn't just me. This happens when the database isn't quite set up.

To go with this, I believe there is an issue with the logic in `[slug].tsx`, lines 16-18

```typescript
    if (!data.length) {
      return 0;
    }
```

I ran into it today. This check will always return `0` for new posts and will never reach the post request logic. @leerob I will make an issue for this.

**Comment by SDBurt** [comment]
@mdixon47 log into your planetscale account, and in the console you can add the table. I believe something like this should work.

```sql
CREATE TABLE views(
`slug`: varchar(128) NOT NULL PRIMARY KEY,
`count` BIGINT NOT NULL
)
```

**Comment by meherranjan** [comment]
I am using SupaBase, tables exist and the request gets completed when I check the network logs in browser. But I keep getting undefined. Not sure why. 

Quick question, why the data will be immediately available in the next statement while, swr is asynchronous?
