### ISSUE TITLE
Add link on social media counter

### ISSUE THREAD

**Issue by lucaspessivaldo** [leerob/leerob.io#574]
When clicking on some of the counters go to the right path.
Add a link to your Twitter, GitHub, and blog when clicking on the counter.

![Screenshot from 2023-02-07 20-58-03](https://user-images.githubusercontent.com/11798065/217395924-fd8ea852-14df-46cd-adad-6c8628e43f77.png)

**Comment by leerob** [comment]
Done, thanks!
