### ISSUE TITLE
Webpage reloads on every route change

### ISSUE THREAD

**Issue by bhagyamudgal** [leerob/leerob.io#580]
When we click on any route, for example, blog - the website reloads, which should not happen when we build a SPA.

**Comment by leerob** [comment]
Hey! Next.js renders every route from the server. Routes are prefetched, using `next/link`, to make navigation between pages feel instantaneous (similar to a SPA). But fundamentally every single you access a route, it's returning some HTML from the server on-demand.

**Comment by bhagyamudgal** [comment]
Got it man, thanks!

**Comment by bhagyamudgal** [comment]
If it is statically generated, then it will not reload, right?

**Comment by leerob** [comment]
It depends -> https://beta.nextjs.org/docs/data-fetching/revalidating
