### ISSUE TITLE
hey Lee what if we have million of images like you use *

### ISSUE THREAD

**Issue by itsanishjain** [leerob/leerob.io#585]
I know you use it because you want to show us the code.

My question is about what if we are building a huge E-commerce store and there we are fetching products that will fail.

Can you guide me to a better codebase? I know there is

- I guess pagination is 1 option but again we can't send params to this so is it we need client-side rendering than

this blog raises the issue but I don't thinks talks about the a good solution 

https://vercel.com/blog/nextjs-server-side-rendering-vs-static-generation

**Comment by leerob** [comment]
Here's an example that could take a ton of images!

https://vercel.com/templates/next.js/image-gallery-starter
