### ISSUE TITLE
Tweet count api error, can you help to solve this error

### ISSUE THREAD

**Issue by 0xNaim** [leerob/leerob.io#587]
Function that copied from your code
```
export async function getTweetCount() {
  if (!process.env.NEXT_PUBLIC_TWITTER_API_TOKEN) {
    return 0;
  }

  const response = await fetch(
    `https://api.twitter.com/2/users/by/username/${process.env.NEXT_PUBLIC_TWITTER_USERNAME}?user.fields=public_metrics`,
    { headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_TWITTER_API_TOKEN}` } }
  );
  const { data } = await response.json();
  return Number(data.public_metrics.tweet_count);
}
```
Calling the function
```
 // Get tweet count
  const getTweets = async () => {
    const tweetCount = await getTweetCount();
    setTotalTweet(tweetCount);
  };
```
```
  useEffect(() => {
    getTweets();
  }, []);
```
It's giving me this error
![error](https://res.cloudinary.com/dbnyrcetn/image/upload/v1677594127/error_33f2f84330.png?updated_at=2023-02-28T14:22:37.929Z)
![error](https://res.cloudinary.com/dbnyrcetn/image/upload/v1677594208/error2_fa53eb26f1.png?updated_at=2023-02-28T14:23:57.785Z)

I can't figure out why it's not working, can you help me to fix this error?

**Comment by alex289** [comment]
In your screenshot there is no Authorization header and the response 401 - Unauthorized seems like there is something missing

**Comment by 0xNaim** [comment]
Yeah, but I can't figure out what is missing. username and API token all are valid, but still getting 401 error. can you give me solution code? It will benefit me a lot.

**Comment by 0xNaim** [comment]
Can you try it yourself and give me solutions, please

**Comment by alex289** [comment]
Your code works for me. Make sure you have setup your key correctly and male sure it's getting added in your request here
`headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_TWITTER_API_TOKEN}` }`

**Comment by 0xNaim** [comment]
I created fresh repo, but still same problem. This code just kidding with me.

![code1](https://res.cloudinary.com/dbnyrcetn/image/upload/v1677606052/err1_61828fba74.png?updated_at=2023-02-28T17:41:21.323Z)
![code 2](https://res.cloudinary.com/dbnyrcetn/image/upload/v1677606100/err2_c39cf4eb61.png?updated_at=2023-02-28T17:42:09.525Z)

I am tired to solve this weird error 🥵

**Comment by alex289** [comment]
Thats odd. Maybe without this cors and Access-Control stuff

**Comment by 0xNaim** [comment]
I tried but still not working

**Comment by alex289** [comment]
Maybe this
https://stackoverflow.com/questions/60151402/i-am-facing-an-error-neterr-aborted-401-unauthorized

**Comment by leerob** [comment]
I agree, it seems like an issue with your Twitter API setup or auth token.

**Comment by ech761** [comment]
Message https://t.me/boydtech on telegram he’s the best.. few days ago he helped me log back into my account

**Comment by 0xNaim** [comment]
There is no issue with API or token, when I move this code next.js /pages/api path then this code works but this code not working in the component
