### ISSUE TITLE
[Question] How to calculate the navItem's x, y, w variables in /components/sidebar.tsx?

### ISSUE THREAD

**Issue by hecker** [leerob/leerob.io#593]
Hi, when adding new pages and therefore also new navbar items, I have the problem that the design isn't proper. How can I calculate the right numbers for x, y, w? Or could there be a way to make it adaptive on the height and width of the characters?

<img width="219" alt="Screenshot 2023-03-14 at 07 45 38" src="https://user-images.githubusercontent.com/23746655/224918154-df741654-c271-43d2-af8e-3a4afd83acb2.png">

**Comment by leerob** [comment]
Check this out! https://github.com/leerob/leerob.io/pull/586
