### ISSUE TITLE
planetscale database

### ISSUE THREAD

**Issue by Sekomer** [leerob/leerob.io#601]
Hi!

I've created a database using the Planetscale with the following command,

```
create table views (
  id int not null auto_increment primary key,
  slug varchar(255) not null,
  count int not null
)
```

when I refresh the page while looking into one of the blogs, its giving me an runtime error toast, am I creating the database correctly? or is there a different problem?

Im using `pnpm dev` and when I click to one of the blogs it works fine, it shows errors when refresh at that point

**Comment by hecker** [comment]
Shouldn't the primary key be declared in another line? Something like:

```
create table views (
  id int not null auto_increment,
  slug varchar(255) not null,
  count int not null,
  primary key (id)
)
```

**Comment by markus-codechefs** [comment]
In general I found very little instructions concerning the inital setup. 
- What actions other than creating a Planetscale db must be executed?
- Can the connection string be placed in the .env? Seems to me to be secret worthy.

**Comment by z4nr34l** [comment]
@Sekomer if case is solved - please close the issue, thanks! :D

If not - let us know so we would be able to help.

**Comment by leerob** [comment]
Looks like it's solved 😄

**Comment by Sekomer** [comment]
it's solved thanks 😄
