### ISSUE TITLE
Twitter API failing

### ISSUE THREAD

**Issue by rlogank** [leerob/leerob.io#605]
I've got my bearer token from the Twitter Developer portal with appropriate permissions and callback URL set to localhost:3000, and plugged into my .env, yet the only thing I can get back from the Twitter API is 403 Forbidden.

```
TypeError: Cannot read properties of undefined (reading 'public_metrics')
    at getTweetCount (webpack-internal:///(sc_server)/./lib/metrics.tsx:36:24)
    at async Promise.all (index 2)
    at HomePage (webpack-internal:///(sc_server)/./app/page.tsx:24:42)
```

I've tried seemingly everything to get this work working. Is this my wrongdoing, or is this Twitter shenanigans? Thanks in advance!

**Comment by chris-nowicki** [comment]
@rlogank do you have a free tier account?

**Comment by XahidEx** [comment]
Also can't even read Tweets. Facing this error for a week. (not just me, many people are facing the same issues) 😪

**Comment by leerob** [comment]
You can also use https://github.com/vercel-labs/react-tweet
