### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by XahidEx** [leerob/leerob.io#613]
Can anyone please share the guestbook schema correctly? Because I've faced several issues. This is my current schema
```
CREATE TABLE `guestbook` (
	`id` int NOT NULL AUTO_INCREMENT,
	`body` varchar(255),
	`email` varchar(255),
	`created_by` varchar(255),
	`updated_at` varchar(255),
	PRIMARY KEY (`id`)
)
```

**Comment by chris-nowicki** [comment]
Hi @XahidEx,

One thing I am noticing is your `updated_at` field.  it should be `TIMESTAMP NOT NULL DEFAULT NOW()` instead of `varchar(255)`.

```
CREATE TABLE guestbook (
	id int NOT NULL AUTO_INCREMENT,
	body varchar(255),
	email varchar(255),
	created_by varchar(255),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`id`)
);
```

give that a try and let me know if it works.  Next thing I would look at would be how you implemented the `guestbook.ts` file.

**Comment by XahidEx** [comment]
> 

I've even tried with it. & It is the same as this repo. But I've having issue. When I manually input data, It shows on the guestbook page. But It doesn't work when I try normally. When I signin write something and sign, It doesn't really push. It gets stuck. And when I refresh the page. It's the same as before. (views table works fine & also existing guestbook entries also shows)

**Comment by XahidEx** [comment]
![20230513_231247](https://github.com/leerob/leerob.io/assets/88249321/d6c92f1f-fbbd-4dfd-8498-623dcd8472ae)
🙂🙂
