### ISSUE TITLE
Hydration Error in blog (Structured Data)

### ISSUE THREAD

**Issue by z4nr34l** [leerob/leerob.io#619]
There is hydration error on blog posts with structured data.

Because of that there are some features in search engines that are not working as bots are getting html-encoded JSON instead of JSON.

PR with fix in few minutes :D

**Comment by XahidEx** [comment]
Also having the same issue ⚠️

**Comment by z4nr34l** [comment]
Just as you had seen in closed merge - Lee fixed this in new version of website ;)

**Comment by z4nr34l** [comment]
I see that it is fixed in Lee's repo in a bit other way, please check if your microdata script tag looks like this:

```tsx
<script type="application/ld+json" suppressHydrationWarning>
    {JSON.stringify(post.structuredData)}
</script>
```
