### ISSUE TITLE
Image zoom on homepage

### ISSUE THREAD

**Issue by z4nr34l** [leerob/leerob.io#646]
Hey @leerob do you want it? :D

I think that would be pretty useful as I was reflexively trying to click on them.

**Comment by z4nr34l** [comment]
I can make PR today If you need that ;)

**Comment by christianavi** [comment]
That would be great. He can accept it if he wants to, but at least we could see the PR, regardless if he accepts it or not.

**Comment by z4nr34l** [comment]
Ready ;)

**Comment by leerob** [comment]
Thanks, but I'm okay without this 🙏
