### ISSUE TITLE
Error: Table 'leeroy.views' doesn't exist when trying to go to the blog page

### ISSUE THREAD

**Issue by benjifriedman** [leerob/leerob.io#658]
I think this has to do with some kind of setup in PlanetScale? But there are no instructions what tables should be set up there or how.

> Unhandled Runtime Error
> Error: target: leeroy.-.primary: vttablet: rpc error: code = NotFound desc = Table 'leeroy.views' doesn't exist (errno 1146) (sqlstate 42S02) (CallerID: q6x8y19tq4aqikxgaz2c): Sql: "select slug, `count` from views", BindVars: {REDACTED}

app/blog/page.tsx (13:19) @ BlogPage
```
  11 | 
  12 | export default async function BlogPage() {
> 13 | const allViews = await getViewsCount();
     |                 ^
  14 | 
  15 | return (
  16 |   <section>
```

**Comment by MarcoPeretti** [comment]
Hello,

I run in the same problem and created the following table:

CREATE TABLE `views` (
	`slug` varchar(255) NOT NULL,
	`count` int NOT NULL,
	PRIMARY KEY (`slug`)
) 

HTH

Marco

**Comment by leerob** [comment]
Added schema to the README
