### ISSUE TITLE
Geist does not work with the canary version ?

### ISSUE THREAD

**Issue by farid98** [leerob/leerob.io#677]
So getting this build error - indicating that Geist does not work with the canary version. 

Am I missing something ? I did copy over the files so have I messed up a setting ? 

While resolving: geist@1.1.0
npm ERR! Found: next@14.0.4-canary.16
npm ERR! node_modules/next
npm ERR!   next@"14.0.4-canary.16" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^13.2 || ^14" from geist@1.1.0
npm ERR! node_modules/geist
npm ERR!   geist@"1.1.0" from the root project

**Comment by farid98** [comment]
OK So I just noticed in the ppm-lock.yaml file there is a special handling for this. I was using npm
 so that's probably the issue here.


  /geist@1.1.0(next@14.0.4-canary.6):
    resolution: {integrity: sha512-UwZH+ekwAt1T5XYlviFD+jUXFeRRawDDT8RtpJ//IHTPXlVIO6BCcZ8M0Pxg1K/FT3H8HLn3KJqMsPLHbo1HNg==}
    peerDependencies:
      next: ^13.2 || ^14
    dependencies:
      next: 14.0.4-canary.6(react-dom@18.2.0)(react@18.2.0)
    dev: false

**Comment by leerob** [comment]
I can't reproduce this one
