### ISSUE TITLE
Blog publishedAt date from mdx frontmatter appears one day behind on the site

### ISSUE THREAD

**Issue by andrewheekin** [leerob/leerob.io#681]
Since javascript parses 'YYYY-MM-DD' formatted strings to have UTC-0 by default, the `formatDate` helper function within `blog/[slug]/page.tsx` returns the parsed YYYY-MM-DD date one day behind. For example, in the US Eastern Standard timezone `new Date('2023-12-11')` will return 2023-12-10T19:00:00

**Comment by andrewheekin** [comment]
(ps, this blog template is so great, thanks @leerob !)

**Comment by leerob** [comment]
Thank you!
