### ISSUE TITLE
Creating a public template

### ISSUE THREAD

**Issue by huydhoang** [leerob/leerob.io#686]
Hi Rob,
I’ve been following your content for a while now and this repo has given me a lot to learn from. Since you called it “a breakable toy” and made a lot of changes over the years, I’m wondering if we could collab to create a public template with only the essential stable features and slower pace of change? I imagine it to be a great contribution to the community especially the new inexperienced devs who just started their own journey.

It’d be immensely helpful if you could give me some guidance on which features to keep and possibly have a kanban board created to keep track of tasks (if you’re interested in such a project).

For example, I really liked your choice of moving back to MDX and querying the posts with pure Node.js, very minimalist and efficient. But I’m not sure about other features as I’m not that experienced and some might be just your trial but no where could I find a project roadmap.

**Comment by leerob** [comment]
Hey! Glad this has been helpful. I like to keep the faster pace here and try out new features, and plan to keep doing that 😄 

I don't have the capacity to run this as a template or roadmap, but keeping this open source so people can learn from it.

**Comment by huydhoang** [comment]
@leerob Thank you for your response. I got what you’re saying about the way you intend this to be. I guess it’s time I start reading the code base end to end and figure out what I can learn from yours and build for myself. I’m still glad that I asked.
