### ISSUE TITLE
Edge Function "og" size is too big.

### ISSUE THREAD

**Issue by briangflett** [leerob/leerob.io#693]
First, many thanks for sharing your work.  Very helpful to those of us that are learning!!

I have copied your repo, run setup to clean the data, and am trying to host the result in my Vercel hobby account.  I am getting the following deployment error  
"The Edge Function "og" size is 1.18 MB and your plan size limit is 1 MB"

Any suggestions for what I should remove?  
Public Repo:    https://github.com/briangflett/nptechadvisor
Deployment:    https://vercel.com/briangflett/nptechadvisor/21ojisBXpbrdRQM2hie1vbmZWh5a?filter=all

By the way, I had to add https://github.com/briangflett/nptechadvisor/blob/main/.npmrc to the root directory to get it to install with the canary version of Next.

**Comment by leerob** [comment]
You could remove the edge runtime from the dynamic OG image I'm using. You likely want to do that anyway, since it's using my OG background 😄

**Comment by briangflett** [comment]
Thanks both.  I'll try updating to the latest canary.  How do I remove the edge runtime from the dynamic OG image?

**Comment by briangflett** [comment]
I removed the background image from the OG route and updated to the latest canary version of Next, and now I am able to host.  Many thanks !!!

**Comment by briangflett** [comment]
I removed the background image from the OG route and updated to the latest canary version of Next, and now I am able to host. Many thanks !!!
