### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by Tytan-Codes-Alt** [leerob/leerob.io#704]
I started it and after editing it, it gives me this error

![image](https://github.com/leerob/leerob.io/assets/147543120/2db71ee4-d2c6-4d24-80f4-c3aaba9397d9)

**Comment by Tytan-Codes-Alt** [comment]
After updating the nextjs version, i get this error:

![image](https://github.com/leerob/leerob.io/assets/147543120/a9c01039-a54d-46db-82c6-144ca03e2255)

**Comment by Tytan-Codes-Alt** [comment]
@leerob

**Comment by marc0002** [comment]
> I started it and after editing it, it gives me this error
> 
> ![image](https://private-user-images.githubusercontent.com/147543120/309337105-2db71ee4-d2c6-4d24-80f4-c3aaba9397d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTQ3OTksIm5iZiI6MTcxMTIxNDQ5OSwicGF0aCI6Ii8xNDc1NDMxMjAvMzA5MzM3MTA1LTJkYjcxZWU0LWQyYzYtNGQyNC04MGY0LWMzYWFiYTkzOTdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNzIxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTkyNDc0ZDI4YTFiNTllZWEwOTk5NGIyOTYyNTM1OGE0OWRhY2ZmM2YyMGVmYjAzZjQxMzA1M2FhODY3NzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.10PlWKPxMESUhcFxsdV19OeZqL--xUex4WfmpMLwshs)


Try deleting these 4 lines from `layout.tsx`.
![image](https://github.com/leerob/leerob.io/assets/82544763/30b50ef5-4bec-44c9-8465-209eaa49ef6f)

**Comment by leerob** [comment]
I unfortunately cannot reproduce this - can you start from the fresh repo on main?
