### ISSUE TITLE
deployed but seeing base template

### ISSUE THREAD

**Issue by rohitbommisetti** [leerob/leerob.io#708]
hey leerob!
thank you for open sourcing your template! wanted to dip my toes in vercel and learn and use this template as a base. i've been running into an issue where i deployed it to vercel but see the base template instead of my code in app.tsx? would you know what is causing this? 
my repo: https://github.com/rohitbommisetti/nextjs-portfolio
my deployed site: https://nextjs-portfolio-5b60pheqn-rohitbommisettis-projects.vercel.app/
would love your quick take on this!
thanks,
rohit

**Comment by leerob** [comment]
It's based on this env var: https://github.com/leerob/leerob.io/blob/main/.env#L1

Remove this and you should be good!

**Comment by rohitbommisetti** [comment]
figured it out, thanks!
