### ISSUE TITLE
Internal server error when posting message in guestbook

### ISSUE THREAD

**Issue by SugarDarius** [leerob/leerob.io#721]
Hi @leerob 👋🏻 

I'm opening an issue as I wanted to post a message in the guestbook but I got an internal server error 😢 
Here's a screen recording showing the issue end to end 👇🏻 

[leerobio_internal_server_error_guestbook.webm](https://github.com/leerob/leerob.io/assets/3740000/29a15f8c-0d85-4c7f-a78b-e8ef7007b2cc)

And here's the response preview I got from the route `https://leerob.io/guestbook`:
```
0:["$@1",["pgcEhzCRL54nq3Fzh8oR4",null]]
1:E{"digest":"4188559564"}
```

Let me know if I can help to provide more insights 🙂 

Thanks,
Aurélien

**Comment by leerob** [comment]
Moved to a different design: https://github.com/leerob/leerob.io/pull/727

**Comment by SugarDarius** [comment]
@leerob thanks for the update 🙏🏻 

Indeed the design very different 😅 
I love the work on the Transition API it's neat!
